create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  text text not null,
  category text not null default '研究',
  priority text not null default '中',
  done boolean not null default false,
  notes text not null default '',
  due_date date,
  view text not null default 'today',
  linked_paper_title text,
  linked_paper_link text,
  estimated_minutes integer not null default 0,
  subtasks jsonb not null default '[]'::jsonb,
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.tasks
  add column if not exists notes text not null default '',
  add column if not exists due_date date,
  add column if not exists view text not null default 'today',
  add column if not exists linked_paper_title text,
  add column if not exists linked_paper_link text,
  add column if not exists estimated_minutes integer not null default 0,
  add column if not exists subtasks jsonb not null default '[]'::jsonb,
  add column if not exists completed_at timestamptz;

create table if not exists public.journals (
  id bigint generated by default as identity primary key,
  date text not null,
  content text not null,
  tags text[] not null default array['随记'],
  created_at timestamptz not null default now()
);

create table if not exists public.reading_library (
  id bigint generated by default as identity primary key,
  title text not null,
  authors text,
  date text,
  link text not null,
  pdf_url text,
  source text,
  summary text,
  doi text,
  citations integer default 0,
  level text,
  paper_type text,
  saved_at text not null default to_char(now(), 'YYYY-MM-DD'),
  created_at timestamptz not null default now(),
  unique (link)
);

alter table public.reading_library
  add column if not exists status text not null default '未读',
  add column if not exists tags text[] not null default array['待精读'],
  add column if not exists priority text not null default '中',
  add column if not exists ai_card text,
  add column if not exists research_plan text,
  add column if not exists personal_rating integer default 0,
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.reader_notes (
  id bigint generated by default as identity primary key,
  paper_link text not null,
  paper_title text not null,
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.reader_highlights (
  id bigint generated by default as identity primary key,
  paper_link text not null,
  paper_title text not null,
  text text not null,
  color text not null default '#fef3c7',
  created_at timestamptz not null default now()
);

create table if not exists public.focus_sessions (
  id bigint generated by default as identity primary key,
  task_id bigint,
  task_text text not null,
  minutes integer not null default 25,
  mode text not null default 'WORK',
  created_at timestamptz not null default now()
);

alter table public.tasks enable row level security;
alter table public.journals enable row level security;
alter table public.reading_library enable row level security;
alter table public.reader_notes enable row level security;
alter table public.reader_highlights enable row level security;
alter table public.focus_sessions enable row level security;

drop policy if exists "Allow anonymous task reads" on public.tasks;
drop policy if exists "Allow anonymous task inserts" on public.tasks;
drop policy if exists "Allow anonymous task updates" on public.tasks;
drop policy if exists "Allow anonymous task deletes" on public.tasks;

create policy "Allow anonymous task reads"
on public.tasks for select
to anon
using (true);

create policy "Allow anonymous task inserts"
on public.tasks for insert
to anon
with check (true);

create policy "Allow anonymous task updates"
on public.tasks for update
to anon
using (true)
with check (true);

create policy "Allow anonymous task deletes"
on public.tasks for delete
to anon
using (true);

drop policy if exists "Allow anonymous journal reads" on public.journals;
drop policy if exists "Allow anonymous journal inserts" on public.journals;
drop policy if exists "Allow anonymous journal deletes" on public.journals;

create policy "Allow anonymous journal reads"
on public.journals for select
to anon
using (true);

create policy "Allow anonymous journal inserts"
on public.journals for insert
to anon
with check (true);

create policy "Allow anonymous journal deletes"
on public.journals for delete
to anon
using (true);

drop policy if exists "Allow anonymous library reads" on public.reading_library;
drop policy if exists "Allow anonymous library inserts" on public.reading_library;
drop policy if exists "Allow anonymous library deletes" on public.reading_library;
drop policy if exists "Allow anonymous library updates" on public.reading_library;

create policy "Allow anonymous library reads"
on public.reading_library for select
to anon
using (true);

create policy "Allow anonymous library inserts"
on public.reading_library for insert
to anon
with check (true);

create policy "Allow anonymous library deletes"
on public.reading_library for delete
to anon
using (true);

create policy "Allow anonymous library updates"
on public.reading_library for update
to anon
using (true)
with check (true);

drop policy if exists "Allow anonymous reader note reads" on public.reader_notes;
drop policy if exists "Allow anonymous reader note inserts" on public.reader_notes;
drop policy if exists "Allow anonymous reader note deletes" on public.reader_notes;

create policy "Allow anonymous reader note reads"
on public.reader_notes for select
to anon
using (true);

create policy "Allow anonymous reader note inserts"
on public.reader_notes for insert
to anon
with check (true);

create policy "Allow anonymous reader note deletes"
on public.reader_notes for delete
to anon
using (true);

drop policy if exists "Allow anonymous reader highlight reads" on public.reader_highlights;
drop policy if exists "Allow anonymous reader highlight inserts" on public.reader_highlights;
drop policy if exists "Allow anonymous reader highlight deletes" on public.reader_highlights;

create policy "Allow anonymous reader highlight reads"
on public.reader_highlights for select
to anon
using (true);

create policy "Allow anonymous reader highlight inserts"
on public.reader_highlights for insert
to anon
with check (true);

create policy "Allow anonymous reader highlight deletes"
on public.reader_highlights for delete
to anon
using (true);

drop policy if exists "Allow anonymous focus reads" on public.focus_sessions;
drop policy if exists "Allow anonymous focus inserts" on public.focus_sessions;

create policy "Allow anonymous focus reads"
on public.focus_sessions for select
to anon
using (true);

create policy "Allow anonymous focus inserts"
on public.focus_sessions for insert
to anon
with check (true);

do $$
begin
  alter publication supabase_realtime add table public.tasks;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.journals;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.reading_library;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.reader_notes;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.reader_highlights;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.focus_sessions;
exception
  when duplicate_object then null;
end $$;

create table if not exists public.insights (
  id bigint generated by default as identity primary key,
  type text not null,
  category text not null,
  title text not null,
  content text not null,
  tags text[] not null default array[]::text[],
  priority text not null default '中',
  source text,
  link text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.insights enable row level security;

drop policy if exists "Allow anonymous insight reads" on public.insights;
drop policy if exists "Allow anonymous insight inserts" on public.insights;
drop policy if exists "Allow anonymous insight deletes" on public.insights;

create policy "Allow anonymous insight reads"
on public.insights for select
to anon
using (true);

create policy "Allow anonymous insight inserts"
on public.insights for insert
to anon
with check (true);

create policy "Allow anonymous insight deletes"
on public.insights for delete
to anon
using (true);

do $$
begin
  alter publication supabase_realtime add table public.insights;
exception
  when duplicate_object then null;
end $$;